version: '3.7'
services:
  boomershub-database:
    image: mysql
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: boomershub-database
    ports:
      - 8080:8080

  aws-services:
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      - SERVICES=s3
      - START_WEB=0
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localhost
      - DEFAULT_REGION=eu-west-1
    volumes:
      - boomershub-aws-services-data:/tmp/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  boomershub-mysql-data:
    driver: local

  boomershub-aws-services-data:
    driver: local
